#!/usr/bin/env bash

##############################################
# Aliases that I use commonly use
##############################################

### Lay the workspace if non existent
if [[ -d ~/workspace ]]; then
    echo "workspace exists - aliases applied..."
else
    echo "workspace created - aliases applied..."
    mkdir -p ~/workspace
fi

### Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias go="cd ~/workspace"

### Check to see if on Mac or *nix and set colorflag variable
if [[ "$(uname)" == "Darwin" ]]; then
    export colorflag="-G"
else
    export colorflag='--color=auto'
fi

### Always use color output for `ls`
alias ls="command ls ${colorflag}" 

### List all files colorized in long format
alias l="ls -lF ${colorflag}"

### Long list to include directory entries whose names begin with a dot (.)
alias ll="ls -al ${colorflag}"

### List all files colorized in long format, excluding . and ..
alias la="ls -lAF ${colorflag}"

### List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

### Always enable colored `grep` output
### Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep="grep ${colorflag}"
alias fgrep="fgrep ${colorflag}"
alias egrep="egrep ${colorflag}"

### Get week number
alias week='date +%V'

### Get day number 
alias day="date +%d"

### Kubernetes aliases
alias k=kubectl
alias kx=kubectx
alias kn=kubens
alias kg="kubectl get"

### Git
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gp="git push"
alias ga="git add"
alias gs="git status"
alias gcm="git commit -m"

### Docker 
alias dps="docker ps --format \nID\t{{.ID}}\nIMAGE\t{{.Image}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.RunningFor}}\nSTATUS\t{{.Status}}\nPORTS\t{{.Ports}}\nNAMES\t{{.Names}}\n"
alias dr="docker run"
alias di="docker images"

### Cloud Foundry (Tanzu Application Service)
alias cfp="cf push"
alias cfl="cf login"

### Concourse 
alias f="fly -t"

### Ansible 
# alias apl="ansible-playbook"
# alias agl="ansible-galaxy"

### End.
