#!/usr/bin/env bash

##############################################
# Aliases that I use commonly use
##############################################

### Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias go="cd ~/workspace"


### Check to see if on Mac or *nix
if [[ "$(uname)" == "Darwin" ]]; then
     export colorflag="-G"
else
    export colorflag='--color=auto'
fi

### Long list to include directory entries whose names begin with a dot (.)
alias ll="ls -al ${colorflag}"

### List all files colorized in long format
alias l="ls -lF ${colorflag}"

### List all files colorized in long format, excluding . and ..
alias la="ls -lAF ${colorflag}"

### List only directories
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

### Always use color output for `ls`
alias ls="command ls ${colorflag}"

### Always enable colored `grep` output
### Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep ${colorflag}'
alias fgrep='fgrep ${colorflag}'
alias egrep='egrep ${colorflag}'

### Get week number
alias week='date +%V'

### Kubernetes aliases
alias k=kubectl
alias kx=kubectx
alias kn=kubens

### Git
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

### Ansible aliases
# alias apl="ansible-playbook"
# alias agl="ansible-galaxy"

### End.
